# AUTO-GENERATED by presentation/patch_business_graphs.py - DO NOT EDIT.
# Business-sanitized variant of V1_1_SM_production_graphs.py for the
# external DICV executive deck: identical data/compute path, display
# strings stripped of model/protocol/internal-field names.
"""
V1_1_SM_production_graphs.py — V1.1 Starter Motor per-VIN production dashboards
================================================================================
34 two-subplot dashboards in the exact visual aesthetic of the alternator
V10.5.3 production graphs (V5.2_ALT/src/V10.5.3_20_5_ALT_production_graphs.py):
top ~72% multi-layer panel, bottom ~28% VSI sparkline, figsize (22,14) @150dpi,
pastel zone backgrounds, #d35400 model line, milestone markers at 25/50/75/100%,
terminal star, vertical reference lines, footer.

HONEST-CONTENT MAPPING (V1.1 ships NO RUL / failure-date forecast):
  TOP PANEL curve  = weekly CAUSAL risk trajectory.  At each week w of a VIN's
    history (starting once >= 12 masked weeks are observed), the frozen 4
    winner features (vsi_withinwk_std_ratio_30d_w, rest_vsi_p05_delta90,
    vsi_range_trend, dip_depth_last90_delta) are recomputed using ONLY data
    <= w (windows re-anchored at the cut — code verbatim from
    V1_1_SM_horizon.py, whose k=0 reconciliation against the frozen matrix is
    exact).  Each point is scored with a LOVO-HONEST model: for VIN i the
    scorer is median-impute -> StandardScaler -> RidgeClassifier(alpha=1.0)
    (closed-form replica, verified <1e-9 vs sklearn in V1_1_SM_nested_ridge.py)
    trained on the OTHER 33 trucks' frozen feature-matrix rows.
  RECALIBRATION CHOICE (documented per spec): per-fold Platt, fit on the
    inner-LOVO decision values of the 33 training trucks computed on the
    FROZEN 4-feature subset.  This mirrors the official per-fold Platt of
    V1_1_SM_nested_ridge.py except that the official pipeline re-screens and
    re-selects the winner subset inside each fold (24/34 folds picked this
    exact 4-feature subset; the rest picked 3-feature siblings), so the k=0
    trajectory score differs slightly from the official OOF prob_recal in the
    non-modal folds.  The reconciliation max|diff| is printed per run.
  ZONES   = V1.1 tiers on the recalibrated-probability axis:
            GREEN < 0.35, AMBER 0.35-0.55, RED >= 0.55 (3 zones, ALT pastels).
  BAND    = no per-week bootstrap band exists; instead the final 10 weeks
            before t_end are shaded as the validated detection window
            ('<=10-week validated warning window', V1_1_SM_horizon_curve.csv k*=10).
  ALERTS  = validated alert fires from V1_1_SM_alert_validation.csv:
            persistence terminal-flag fire week (triangle), A1 crank-burst
            first alarm (thin diamond; only the first alarm date is recorded
            in the CSV), A2 battery-cascade fire week (inverted triangle).
  GAP-MASKING: trajectory and sparkline lines break (NaN) across telemetry
            gaps — no interpolation (established graph-design convention).
  BOTTOM  = weekly vsi_drive_mean (#2c3e50) with p05-p95 fill (#e67e22),
            DICV hlines 28.2 / 26.0 / 24.0, crank-event ticks along the
            bottom edge (failed=red, success=gray; omitted for SMA-dead).

Usage
-----
    py -3 "STARTER MOTOR/V1.1/src/V1_1_SM_production_graphs.py"              # all 34
    py -3 "STARTER MOTOR/V1.1/src/V1_1_SM_production_graphs.py" VIN8_F_SM    # specific

Output:  STARTER MOTOR/V1.1/graphs/V1_1_SM_{VIN_LABEL}_dashboard.png
"""
from __future__ import annotations

import json
import sys
import warnings
from datetime import datetime
from pathlib import Path

import matplotlib
matplotlib.use("Agg")

import matplotlib.dates as mdates
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import numpy as np
import pandas as pd
from scipy import stats
from sklearn.linear_model import LogisticRegression

# Display-level VIN renumbering (2026-06-11): failed VIN1-14 unchanged, NF
# shifted +14 (old VIN1_NF -> VIN15_NF). Data is still loaded/keyed by the
# ORIGINAL labels; only titles, footers and output filenames use the new ones.
from V1_1_SM_vin_display_map import display_label, raw_file_note

warnings.filterwarnings("ignore")
np.random.seed(42)

# ---------------------------------------------------------------------------
# 1. Paths and constants
# ---------------------------------------------------------------------------
ROOT = Path(r"D:\Daimler-starter_motor_alternator_battery\STARTER MOTOR")
RES11 = ROOT / "V1.1" / "results"
DISC = ROOT / "V1.1" / "discovery" / "out"
GRAPHS = ROOT / "V1.1" / "presentation" / "assets"

VERSION = "V1_1_SM"
L40 = 40
MIN_TRAJ_WEEKS = 12          # trajectory starts once >= 12 masked weeks observed
STALE_GAP_DAYS = 21          # no masked week within this window before the cut -> mask point
VALID_HORIZON_WK = 10        # k* = 10 from V1_1_SM_horizon_curve.csv
STEP_MIN_V, STEP_MIN_SNR = 0.5, 2.0
RIDGE_ALPHA = 1.0
FROZEN = ["vsi_withinwk_std_ratio_30d_w", "rest_vsi_p05_delta90",
          "vsi_range_trend", "dip_depth_last90_delta"]
SMA_DEAD_THRESH = 0.01

GAP_VINS = {"VIN1_F_SM": 72, "VIN4_F_SM": 97, "VIN5_F_SM": 32,
            "VIN8_F_SM": 37, "VIN9_F_SM": 142}

# V1.1 tiers (3 zones — same pastel family as ALT, no yellow tier)
TIER_GREEN, TIER_RED = 0.35, 0.55
ZONE_COLORS = {"GREEN": "#a5d6a7", "AMBER": "#ffb74d", "RED": "#ef9a9a"}
TIER_DARK = {"GREEN": "#1b7a3d", "AMBER": "#d35400", "RED": "#8b0000"}

# Plot colours (ALT aesthetic)
CLR_MODEL = "#d35400"
CLR_BAND = "#e67e22"
CLR_VSI_LINE = "#2c3e50"
CLR_VSI_FILL = "#e67e22"
CLR_GREEN = "#27ae60"
CLR_JCO = "#b71c1c"
CLR_PERS = "#8e44ad"
CLR_A1 = "#1565c0"
CLR_A2 = "#c62828"

# DICV thresholds (V)
VSI_NORMAL_RUNNING = 28.2
VSI_UNDERVOLTAGE = 26.0
VSI_MIN_CRANK = 24.0


def tier_of(p: float) -> str:
    return "GREEN" if p < TIER_GREEN else ("AMBER" if p < TIER_RED else "RED")


# ---------------------------------------------------------------------------
# 2. Load inputs (identical sources to V1_1_SM_features.py / V1_1_SM_horizon.py)
# ---------------------------------------------------------------------------
print("Loading weekly caches, crank events, frozen matrix, predictions, alerts...")
wk_all = pd.concat([pd.read_parquet(f) for f in
                    sorted((ROOT / "cache/weekly").glob("V1_SM_weekly_*.parquet"))],
                   ignore_index=True)
wk_all["week"] = pd.to_datetime(wk_all["week"])
ev_all_raw = pd.read_parquet(ROOT / "cache/events/V1_SM_crank_events.parquet")
ev_all = ev_all_raw[ev_all_raw["artifact"] == False].copy()
ev_all["ts_start"] = pd.to_datetime(ev_all["ts_start"])
ev_all["ts_day"] = ev_all["ts_start"].dt.normalize()

fm_v1 = pd.read_csv(ROOT / "results" / "V1_SM_feature_matrix.csv")
vins = fm_v1["vin_label"].tolist()
y = fm_v1["failed"].astype(int).values
assert len(vins) == 34 and y.sum() == 14

dq = pd.read_csv(ROOT / "results" / "V1_SM_data_quality.csv")
T_END = {r["vin_label"]: pd.to_datetime(r["t_end"]) for _, r in dq.iterrows()}

frozen_mat = pd.read_csv(RES11 / "V1_1_SM_feature_matrix.csv")
assert list(frozen_mat["vin_label"]) == vins
preds = pd.read_csv(RES11 / "V1_1_SM_nested_lovo_predictions.csv").set_index("vin_label")
spec = json.loads((RES11 / "V1_1_SM_model_spec.json").read_text())
AUROC_STR = f"{spec['headline']['nested_auroc']:.3f}"

alerts = pd.read_csv(RES11 / "V1_1_SM_alert_validation.csv").set_index("vin_label")
arch = pd.read_csv(DISC / "E2_failed_vin_archetypes.csv").set_index("vin_label")

# Battery-replacement steps (E5) — verbatim selection from V1_1_SM_features.py
steps = pd.read_csv(DISC / "E5_step_changes_all.csv")
steps["step_week"] = pd.to_datetime(steps["step_week"])
bat = steps[(steps["signal"] == "vsi_rest_median")
            & (steps["step_V"] >= STEP_MIN_V) & (steps["snr"] >= STEP_MIN_SNR)]
BAT_STEP = dict(zip(bat["vin_label"], bat["step_week"]))

# SMA-dead cohort — detected from weekly caches EXACTLY as V1_1_SM_features.py
SMA_DEAD = set()
for vin in vins:
    w = wk_all[wk_all["vin_label"] == vin]
    if w["sma_obs_rows"].sum() / max(w["n_rows"].sum(), 1) <= SMA_DEAD_THRESH:
        SMA_DEAD.add(vin)
EXPECTED_DEAD = {"VIN8_F_SM", "VIN9_F_SM", "VIN10_NF_SM", "VIN11_NF_SM",
                 "VIN12_NF_SM", "VIN13_NF_SM", "VIN20_NF_SM"}
assert SMA_DEAD == EXPECTED_DEAD, f"SMA-dead detection drifted: {SMA_DEAD}"
print(f"  SMA-dead cohort ({len(SMA_DEAD)}): {sorted(SMA_DEAD)}")

WK = {v: wk_all[(wk_all["vin_label"] == v) & (wk_all["active_days"] >= 2)]
      .sort_values("week").reset_index(drop=True) for v in vins}
WK_ALL = {v: wk_all[wk_all["vin_label"] == v].sort_values("week").reset_index(drop=True)
          for v in vins}
EV = {v: ev_all[ev_all["vin_label"] == v].sort_values("ts_start") for v in vins}


# ---------------------------------------------------------------------------
# 3. Frozen 4-feature recompute at a causal cut — VERBATIM from V1_1_SM_horizon.py
# ---------------------------------------------------------------------------
def theil_sen(yv, xv):
    m = np.isfinite(yv) & np.isfinite(xv)
    if m.sum() < 4:
        return np.nan
    return float(stats.theilslopes(yv[m], xv[m]).slope)


def frozen_feats(vin, cut):
    """The 4 frozen X1 features computed only from data <= cut (horizon-exact)."""
    wm = WK[vin][WK[vin]["week"] <= cut].tail(L40).reset_index(drop=True)
    f = {"n_wk": len(wm)}
    if len(wm) < 8:
        f.update({k: np.nan for k in FROZEN})
        return f
    win_start = wm["week"].iloc[0]
    wm = wm.copy()
    wm["week_x"] = (wm["week"] - wm["week"].iloc[0]).dt.days / 7.0
    vds = wm["vsi_drive_std"].values.astype(float)

    f["vsi_withinwk_std_ratio_30d_w"] = (
        float(np.nanmean(vds[-4:]) / np.nanmean(vds))
        if np.isfinite(vds).sum() >= 6 and np.nanmean(vds) > 0 else np.nan)

    last12 = wm.tail(12)
    rng = (last12["vsi_drive_p95"] - last12["vsi_drive_p05"]).values.astype(float)
    f["vsi_range_trend"] = (theil_sen(rng, last12["week_x"].values.astype(float))
                            if np.isfinite(rng).sum() >= 6 else np.nan)

    vrp = wm["vsi_rest_p05"].values.astype(float)
    last13, base = vrp[-13:], vrp[:-13]
    base_weeks = wm["week"].values[:-13]
    if vin in BAT_STEP and pd.Timestamp(BAT_STEP[vin]) <= cut:
        post = base[base_weeks >= np.datetime64(BAT_STEP[vin])]
        if np.isfinite(post).sum() >= 4:
            base = post
    if np.isfinite(last13).sum() >= 6 and np.isfinite(base).sum() >= 4:
        f["rest_vsi_p05_delta90"] = float(np.nanmean(last13) - np.nanmean(base))
    else:
        f["rest_vsi_p05_delta90"] = np.nan

    if vin in SMA_DEAD:
        f["dip_depth_last90_delta"] = np.nan
    else:
        ev = EV[vin][EV[vin]["ts_start"] <= cut]
        dbc = (cut.normalize() - ev["ts_day"]).dt.days
        e90 = ev[dbc <= 90]
        base_ev = ev[(ev["ts_start"] >= win_start) & (dbc > 90)]
        d90 = e90["dip_depth"].dropna()
        dbase = base_ev["dip_depth"].dropna()
        f["dip_depth_last90_delta"] = (float(d90.mean() - dbase.mean())
                                       if len(d90) >= 10 and len(dbase) >= 10
                                       else np.nan)
    return f


# ---------------------------------------------------------------------------
# 4. LOVO-honest fold models (frozen 4 features) + per-fold Platt
# ---------------------------------------------------------------------------
def fit_fold_models():
    """For each VIN: ridge params trained WITHOUT that VIN on the frozen matrix
    rows, plus a per-fold Platt fit on the 33-truck inner-LOVO decision values
    (frozen 4-feature subset)."""
    Fm = frozen_mat[FROZEN].values.astype(float)

    def ridge_fit(Xtr, ytr):
        med = np.nanmedian(Xtr, axis=0)
        med = np.where(np.isfinite(med), med, 0.0)
        Xi = np.where(np.isfinite(Xtr), Xtr, med)
        mu, sd = Xi.mean(0), Xi.std(0)
        sd = np.where(sd == 0, 1.0, sd)
        Xs = (Xi - mu) / sd
        yp = 2.0 * ytr - 1.0
        beta = np.linalg.solve(Xs.T @ Xs + RIDGE_ALPHA * np.eye(Xs.shape[1]),
                               Xs.T @ (yp - yp.mean()))
        return med, mu, sd, beta, float(yp.mean())

    models = {}
    for i, vin in enumerate(vins):
        tr = np.arange(len(vins)) != i
        Xtr, ytr = Fm[tr], y[tr]
        med, mu, sd, beta, b0 = ridge_fit(Xtr, ytr)
        # inner LOVO over the 33 training trucks for the Platt fit
        z_in = np.empty(len(ytr))
        for j in range(len(ytr)):
            itr = np.arange(len(ytr)) != j
            m_, u_, s_, b_, c_ = ridge_fit(Xtr[itr], ytr[itr])
            xj = np.where(np.isfinite(Xtr[j]), Xtr[j], m_)
            z_in[j] = ((xj - u_) / s_) @ b_ + c_
        platt = LogisticRegression(C=1e6, max_iter=10000).fit(z_in.reshape(-1, 1), ytr)
        pa, pb = float(platt.coef_[0, 0]), float(platt.intercept_[0])
        models[vin] = (med, mu, sd, beta, b0, pa, pb)
    return models


def score(vin, feat_vec, models):
    med, mu, sd, beta, b0, pa, pb = models[vin]
    x = np.where(np.isfinite(feat_vec), feat_vec, med)
    z = ((x - mu) / sd) @ beta + b0
    return float(1.0 / (1.0 + np.exp(-(pa * z + pb))))


# ---------------------------------------------------------------------------
# 5. Per-VIN causal weekly trajectory
# ---------------------------------------------------------------------------
def compute_trajectory(vin: str, models) -> pd.DataFrame:
    """Risk at cuts t_end - 7k days, k descending (dates ascending); starts once
    >= MIN_TRAJ_WEEKS masked weeks are observed. Stale (telemetry-gap) points
    are flagged so the plotted line breaks instead of interpolating."""
    t_end = T_END[vin]
    wk_dates = WK[vin]["week"]
    rows = []
    k = 0
    while True:
        cut = t_end - pd.Timedelta(days=7 * k)
        f = frozen_feats(vin, cut)
        if f["n_wk"] < MIN_TRAJ_WEEKS:
            break
        p = score(vin, np.array([f[c] for c in FROZEN], float), models)
        cutd = cut.normalize()
        fresh = bool(((wk_dates > cutd - pd.Timedelta(days=STALE_GAP_DAYS))
                      & (wk_dates <= cutd)).any())
        rows.append({"date": cut, "k": k, "p": p, "fresh": fresh, "n_wk": f["n_wk"]})
        k += 1
    return pd.DataFrame(rows).sort_values("date").reset_index(drop=True)


# ---------------------------------------------------------------------------
# 6. Sparkline data (weekly, gap-masked) + daily crank ticks
# ---------------------------------------------------------------------------
def sparkline_weekly(vin: str) -> pd.DataFrame:
    s = WK_ALL[vin].dropna(subset=["vsi_drive_mean"]).sort_values("week")
    if not len(s):
        return s
    return (s.set_index("week")[["vsi_drive_mean", "vsi_drive_p05", "vsi_drive_p95"]]
            .resample("W-MON").asfreq().reset_index())


def crank_tick_days(vin: str):
    ev = EV[vin][EV[vin]["success"].notna()].copy()
    if not len(ev):
        return [], []
    day_fail = ev.groupby("ts_day")["success"].apply(lambda s: (~s.astype(bool)).any())
    fail_days = day_fail[day_fail].index.tolist()
    ok_days = day_fail[~day_fail].index.tolist()
    return ok_days, fail_days


# ---------------------------------------------------------------------------
# 7. Main plotting function — V1.1 dashboard in the ALT 5-layer aesthetic
# ---------------------------------------------------------------------------
def plot_dashboard(vin: str, traj: pd.DataFrame, out_path: Path) -> None:
    is_failed = bool(y[vins.index(vin)])
    pred = preds.loc[vin]
    final_p = float(pred["prob_recal"])
    final_tier = str(pred["tier"])
    gap_days = GAP_VINS.get(vin, 0)
    t_end = T_END[vin]
    jcopen = t_end + pd.Timedelta(days=gap_days)
    al = alerts.loc[vin]
    archetype = str(arch.loc[vin, "archetype"]) if vin in arch.index else "—"
    spark = sparkline_weekly(vin)
    sma_dead = vin in SMA_DEAD

    dates = traj["date"].tolist()
    p_arr = traj["p"].values.astype(float)
    p_plot = np.where(traj["fresh"].values, p_arr, np.nan)   # gap-masked line
    first_data = WK_ALL[vin]["week"].min()
    n_days = int((t_end - first_data).days)
    traj_tier_final = tier_of(p_arr[-1])

    # ------------------------------------------------------------------
    # Figure setup — exact ALT geometry
    # ------------------------------------------------------------------
    fig = plt.figure(figsize=(22, 14), dpi=150, facecolor="white",
                     edgecolor="#cccccc", linewidth=1.5)
    gs = gridspec.GridSpec(2, 1, height_ratios=[72, 28], hspace=0.08,
                           left=0.06, right=0.89, top=0.88, bottom=0.06)
    ax_risk = fig.add_subplot(gs[0])
    ax_spark = fig.add_subplot(gs[1], sharex=ax_risk)
    ax_risk.set_facecolor("white")
    ax_spark.set_facecolor("#fafafa")

    plot_start = first_data - pd.Timedelta(days=10)
    plot_end = max(t_end + pd.Timedelta(days=21), jcopen + pd.Timedelta(days=14))
    ax_risk.set_xlim(plot_start, plot_end)
    ax_risk.set_ylim(0.0, 1.0)

    # ==================================================================
    # TOP SUBPLOT — causal risk trajectory
    # ==================================================================
    # ---- Zone backgrounds: V1.1 tiers on the recalibrated-probability axis ----
    ax_risk.axhspan(0.0, TIER_GREEN, facecolor=ZONE_COLORS["GREEN"], alpha=0.35, zorder=0)
    ax_risk.axhspan(TIER_GREEN, TIER_RED, facecolor=ZONE_COLORS["AMBER"], alpha=0.35, zorder=0)
    ax_risk.axhspan(TIER_RED, 1.0, facecolor=ZONE_COLORS["RED"], alpha=0.35, zorder=0)
    for lab, ymid in (("GREEN", TIER_GREEN / 2), ("AMBER", (TIER_GREEN + TIER_RED) / 2),
                      ("RED", (TIER_RED + 1.0) / 2)):
        ax_risk.text(0.005, ymid, lab, transform=ax_risk.get_yaxis_transform(),
                     fontsize=10, fontweight="bold", color=TIER_DARK[lab],
                     va="center", ha="left", alpha=0.85, zorder=5)
    # Right-edge threshold labels (ALT style)
    for thr, lab, zn in ((TIER_GREEN, f"AMBER {TIER_GREEN:.2f}", "AMBER"),
                         (TIER_RED, f"RED {TIER_RED:.2f}", "RED")):
        ax_risk.axhline(thr, color=TIER_DARK[zn], linewidth=0.7, linestyle=":", alpha=0.5, zorder=1)
        ax_risk.text(mdates.date2num(plot_end) + 1, thr, f"  {lab}",
                     fontsize=9, color=TIER_DARK[zn], va="center", fontweight="bold",
                     clip_on=False,
                     bbox=dict(boxstyle="round,pad=0.15", fc=ZONE_COLORS[zn],
                               ec=TIER_DARK[zn], alpha=0.7, linewidth=0.8))

    # ---- Validated detection window (replaces ALT forecast band, honestly) ----
    win_start = t_end - pd.Timedelta(weeks=VALID_HORIZON_WK)
    ax_risk.axvspan(mdates.date2num(win_start), mdates.date2num(t_end),
                    facecolor=CLR_BAND, alpha=0.12, zorder=1)
    horizon_patch = mpatches.Patch(facecolor=CLR_BAND, alpha=0.25,
                                   label="≤10-week validated warning window")

    # ---- Risk trajectory line (gap-masked, ALT model-line styling) ----
    ax_risk.plot(dates, p_plot, color=CLR_MODEL, linewidth=2.0, linestyle="-",
                 alpha=1.0, zorder=4, label="Weekly vehicle health-risk")
    fin_idx = np.where(np.isfinite(p_plot))[0]
    mk = fin_idx[::4]
    ax_risk.plot([dates[i] for i in mk], p_plot[mk], color=CLR_MODEL, linewidth=0,
                 marker="o", markersize=4.5, markerfacecolor=CLR_MODEL,
                 markeredgecolor="white", markeredgewidth=0.5, zorder=5)

    # ---- Milestones at 25/50/75/100% of the observed trajectory ----
    n_pts = len(traj)
    for pct in (0.25, 0.50, 0.75, 1.0):
        idx = int(round(pct * (n_pts - 1)))
        # nearest fresh point
        if len(fin_idx):
            idx = int(fin_idx[np.argmin(np.abs(fin_idx - idx))])
        ms_date, ms_p = dates[idx], p_arr[idx]
        ms_tier = tier_of(ms_p)
        mc = TIER_DARK[ms_tier]
        ax_risk.plot(ms_date, ms_p, marker="D", markersize=11, markerfacecolor=mc,
                     markeredgecolor="white", markeredgewidth=1.2, zorder=8)
        # stagger above/below by pct, but force below when the point is high
        # (keeps boxes clear of the upper-right legend) and above when low
        if ms_p > 0.75:
            y_off = -0.13
            x_off = -30 if pct in (0.25, 0.75) else 30
        elif ms_p < 0.15:
            y_off = 0.14
            x_off = -30 if pct in (0.25, 0.75) else 30
        elif pct in (0.25, 0.75):
            y_off, x_off = 0.14, -30
        else:
            y_off, x_off = -0.12, 30
        ann_y = float(np.clip(ms_p + y_off, 0.05, 0.88))
        ax_risk.annotate(f"P={ms_p:.2f} | {ms_tier[0]}",
                         xy=(mdates.date2num(ms_date), ms_p),
                         xytext=(mdates.date2num(ms_date) + x_off, ann_y),
                         fontsize=8, fontweight="bold", color=mc,
                         ha="center", va="center",
                         bbox=dict(boxstyle="round,pad=0.3", fc="white", ec=mc,
                                   alpha=0.90, linewidth=1.0),
                         arrowprops=dict(arrowstyle="-|>", color=mc, lw=0.8,
                                         connectionstyle="arc3,rad=0.15"),
                         zorder=9)

    # ---- Alert markers (V1.1-specific layer, only where fired) ----
    def _traj_y(d):
        xs = mdates.date2num(pd.to_datetime(d))
        tx = mdates.date2num(pd.Series(dates))
        return float(np.clip(np.interp(xs, tx, p_arr), 0.03, 0.97))

    alert_handles = []
    if bool(al["pers_fire_end"]) and pd.notna(al["pers_terminal_fire_start"]):
        d = pd.to_datetime(al["pers_terminal_fire_start"])
        ax_risk.plot(d, _traj_y(d), marker="^", markersize=10, markerfacecolor=CLR_PERS,
                     markeredgecolor="white", markeredgewidth=1.0, linestyle="", zorder=9)
        alert_handles.append(Line2D([], [], marker="^", color=CLR_PERS, linestyle="",
                                    markersize=8, label="Sustained electrical-volatility alert"))
    a1f = al["a1_fire"]
    if isinstance(a1f, (bool, np.bool_)) and bool(a1f) and pd.notna(al["a1_first_alarm"]):
        d = pd.to_datetime(al["a1_first_alarm"])
        n_ep = int(al["a1_n_episodes"]) if pd.notna(al["a1_n_episodes"]) else 1
        ax_risk.plot(d, _traj_y(d), marker="d", markersize=9, markerfacecolor=CLR_A1,
                     markeredgecolor="white", markeredgewidth=1.0, linestyle="", zorder=9)
        alert_handles.append(Line2D([], [], marker="d", color=CLR_A1, linestyle="",
                                    markersize=8,
                                    label=f"Crank-anomaly alert (×{n_ep} episodes)"))
    if isinstance(al["a2_fire"], (bool, np.bool_)) and bool(al["a2_fire"]) \
            and pd.notna(al["a2_fire_week"]):
        d = pd.to_datetime(al["a2_fire_week"])
        ax_risk.plot(d, _traj_y(d), marker="v", markersize=10, markerfacecolor=CLR_A2,
                     markeredgecolor="white", markeredgewidth=1.0, linestyle="", zorder=9)
        alert_handles.append(Line2D([], [], marker="v", color=CLR_A2, linestyle="",
                                    markersize=8, label="Battery-cascade alert"))

    # ---- Terminal star at last observation, colored by final tier ----
    term_color = TIER_DARK[final_tier]
    ax_risk.plot(dates[-1], p_arr[-1], marker="*", markersize=16,
                 markerfacecolor=term_color, markeredgecolor="white",
                 markeredgewidth=1.5, zorder=10, label="Terminal observation")
    if is_failed:
        term_label = (f"Last Obs: {t_end:%Y-%m-%d}\nFailure date: {jcopen:%Y-%m-%d}\n"
                      f"Final P: {final_p:.2f} ({final_tier})")
    else:
        term_label = (f"Last Obs: {t_end:%Y-%m-%d}\nStatus: Active\n"
                      f"Final P: {final_p:.2f} ({final_tier})")
    # high-risk terminals annotate BELOW the star to stay clear of the legend
    if p_arr[-1] >= 0.55:
        ann_y, ann_va, ann_rad = float(np.clip(p_arr[-1] - 0.20, 0.10, 0.80)), "top", 0.2
    else:
        ann_y, ann_va, ann_rad = float(np.clip(p_arr[-1] + 0.14, 0.10, 0.80)), "bottom", -0.2
    ax_risk.annotate(term_label,
                     xy=(mdates.date2num(dates[-1]), p_arr[-1]),
                     xytext=(mdates.date2num(dates[-1]) - 40, ann_y),
                     fontsize=8, fontweight="bold", color=term_color,
                     ha="center", va=ann_va,
                     bbox=dict(boxstyle="round,pad=0.4", fc="white", ec=term_color,
                               alpha=0.92, linewidth=1.2),
                     arrowprops=dict(arrowstyle="-|>", color=term_color, lw=1.2,
                                     connectionstyle=f"arc3,rad={ann_rad}"),
                     zorder=10)

    # ---- Vertical reference lines ----
    _vf = 7.5
    ax_risk.axvline(mdates.date2num(first_data), color="#27ae60", linewidth=1.3,
                    linestyle=":", zorder=3, alpha=0.8)
    ax_risk.text(mdates.date2num(first_data), 0.98, f" First Data {first_data:%Y-%m-%d}",
                 fontsize=_vf, color="#27ae60", rotation=90, va="top", ha="left", zorder=5)
    ax_risk.axvline(mdates.date2num(t_end), color="gray", linewidth=1.3,
                    linestyle="--", zorder=3, alpha=0.7)
    ax_risk.text(mdates.date2num(t_end), 0.60, f" Last Data {t_end:%Y-%m-%d}",
                 fontsize=_vf, color="gray", rotation=90, va="center", ha="left", zorder=5)
    if is_failed:
        ax_risk.axvline(mdates.date2num(jcopen), color=CLR_JCO, linewidth=1.4,
                        linestyle="--", zorder=3)
        ax_risk.text(mdates.date2num(jcopen), 0.38, f" Failure {jcopen:%Y-%m-%d}",
                     fontsize=_vf, color=CLR_JCO, fontweight="bold",
                     rotation=90, va="center", ha="left", zorder=5)
    if gap_days > 0:
        ax_risk.axvspan(mdates.date2num(t_end), mdates.date2num(jcopen),
                        facecolor="none", edgecolor="#757575", hatch="///",
                        lw=0.0, alpha=0.45, zorder=1)
        mid = t_end + (jcopen - t_end) / 2
        gap_txt = f"silent gap {gap_days}d"
        box = dict(boxstyle="round,pad=0.3", fc="white", ec="#757575", alpha=0.9)
        if gap_days >= 60:
            ax_risk.text(mdates.date2num(mid), 0.50, gap_txt, ha="center", va="center",
                         fontsize=8.5, color="#555555", fontweight="bold", bbox=box,
                         zorder=6)
        else:
            # narrow gap: annotate low and to the left (clear of the terminal box)
            ax_risk.annotate(gap_txt, xy=(mdates.date2num(mid), 0.28),
                             xytext=(mdates.date2num(t_end - pd.Timedelta(days=25)), 0.22),
                             ha="right", va="center", fontsize=8.5, color="#555555",
                             fontweight="bold", bbox=box,
                             arrowprops=dict(arrowstyle="->", color="#757575", lw=1.0),
                             zorder=6)

    # ---- Special annotations ----
    if vin == "VIN9_F_SM":
        ax_risk.text(0.02, 0.80, "no advance signal — telemetry ceased before failure",
                     transform=ax_risk.transAxes, fontsize=10, fontweight="bold",
                     color="#8b0000", ha="left", va="center",
                     bbox=dict(boxstyle="round,pad=0.4", fc="#fdecea", ec="#8b0000",
                               alpha=0.92, linewidth=1.2), zorder=10)
    if sma_dead:
        ax_risk.text(0.02, 0.03, "crank telemetry not available for this vehicle",
                     transform=ax_risk.transAxes, fontsize=8.5, style="italic",
                     color="#666666", ha="left", va="bottom", zorder=10)

    # ---- Final risk box, lower-right (ALT ridge-risk style) ----
    ax_risk.text(0.97, 0.06, f"Final Risk: {final_p:.0%} ({final_tier})",
                 transform=ax_risk.transAxes, fontsize=9, fontweight="bold",
                 color=term_color, ha="right", va="bottom",
                 bbox=dict(boxstyle="round,pad=0.5", fc="white", ec=term_color,
                           alpha=0.92, linewidth=1.5), zorder=10)

    # ---- Labels, grid, legend (top) ----
    ax_risk.set_ylabel("Failure-risk score", fontsize=13, fontweight="bold")
    ax_risk.grid(True, which="major", color="#e0e0e0", linewidth=0.5, zorder=0)
    ax_risk.set_axisbelow(True)
    plt.setp(ax_risk.get_xticklabels(), visible=False)

    handles1, labels1 = ax_risk.get_legend_handles_labels()
    zone_patches = [
        mpatches.Patch(facecolor=ZONE_COLORS["GREEN"], alpha=0.5, label="GREEN <0.35"),
        mpatches.Patch(facecolor=ZONE_COLORS["AMBER"], alpha=0.5, label="AMBER 0.35-0.55"),
        mpatches.Patch(facecolor=ZONE_COLORS["RED"], alpha=0.5, label="RED >=0.55"),
    ]
    all_h = handles1 + alert_handles + [horizon_patch] + zone_patches
    all_l = [h.get_label() for h in all_h]
    ax_risk.legend(all_h, all_l, loc="upper right", fontsize=8.5, framealpha=0.88,
                   edgecolor="#cccccc", fancybox=True, ncol=2, borderpad=0.8)

    # ==================================================================
    # BOTTOM SUBPLOT — weekly VSI sparkline + crank ticks
    # ==================================================================
    if len(spark):
        ax_spark.fill_between(spark["week"], spark["vsi_drive_p05"],
                              spark["vsi_drive_p95"], color=CLR_VSI_FILL,
                              alpha=0.22, label="Operating-voltage range (P5-P95)")
        ax_spark.plot(spark["week"], spark["vsi_drive_mean"], color=CLR_VSI_LINE,
                      linewidth=1.2, alpha=0.9, label="Avg. operating voltage (weekly)")

    # DICV reference lines with right-edge labels (ALT style)
    for v_thr, clr, lab in ((VSI_NORMAL_RUNNING, CLR_GREEN, f"Normal: {VSI_NORMAL_RUNNING}V"),
                            (VSI_UNDERVOLTAGE, "#c0392b", f"Undervoltage: {VSI_UNDERVOLTAGE}V"),
                            (VSI_MIN_CRANK, "#8b0000", f"Crank min: {VSI_MIN_CRANK}V")):
        ax_spark.axhline(v_thr, color=clr, linewidth=1.2, linestyle="--", alpha=0.6, zorder=2)
        ax_spark.text(mdates.date2num(plot_end) + 1, v_thr, f"  {lab}",
                      fontsize=8, color=clr, va="center", clip_on=False)

    # Crank-event ticks along the bottom edge (replaces ALT GED=2 ticks)
    if sma_dead:
        ax_spark.text(0.01, 0.06, "crank events not recorded for this vehicle",
                      transform=ax_spark.transAxes, fontsize=8, style="italic",
                      color="#666666", ha="left", va="bottom", zorder=6)
    else:
        ok_days, fail_days = crank_tick_days(vin)
        if ok_days:
            ax_spark.scatter(ok_days, [20.4] * len(ok_days), color="#9e9e9e",
                             marker="|", s=40, alpha=0.55, zorder=4,
                             label="successful cranks (day)")
        if fail_days:
            ax_spark.scatter(fail_days, [20.4] * len(fail_days), color="#e74c3c",
                             marker="|", s=70, alpha=0.85, zorder=5,
                             label="failed crank day")

    # Mirror vertical reference lines
    ax_spark.axvline(mdates.date2num(first_data), color="#27ae60", linewidth=0.8,
                     linestyle=":", alpha=0.6)
    ax_spark.axvline(mdates.date2num(t_end), color="gray", linewidth=0.8,
                     linestyle="--", alpha=0.5)
    if is_failed:
        ax_spark.axvline(mdates.date2num(jcopen), color=CLR_JCO, linewidth=0.8,
                         linestyle="--", alpha=0.6)
    if gap_days > 0:
        ax_spark.axvspan(mdates.date2num(t_end), mdates.date2num(jcopen),
                         facecolor="none", edgecolor="#bdbdbd", hatch="///",
                         lw=0.0, alpha=0.4, zorder=1)

    ax_spark.set_ylim(19.5, 32.5)
    ax_spark.set_ylabel("Voltage (V)", fontsize=13, fontweight="bold")
    ax_spark.set_xlabel("Timeline", fontsize=13, fontweight="bold")
    ax_spark.grid(True, which="major", color="#e0e0e0", linewidth=0.5, zorder=0)
    ax_spark.set_axisbelow(True)
    ax_spark.legend(loc="upper right", fontsize=8.5, framealpha=0.85, ncol=4)

    ax_spark.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m"))
    ax_spark.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
    plt.setp(ax_spark.xaxis.get_majorticklabels(), rotation=45, ha="right", fontsize=10)
    plt.setp(ax_spark.yaxis.get_majorticklabels(), fontsize=10)
    plt.setp(ax_risk.yaxis.get_majorticklabels(), fontsize=10)

    # ==================================================================
    # Title, subtitle, footer (ALT styling)
    # ==================================================================
    disp_label = display_label(vin)
    fig.suptitle(f"Starter Motor Failure-Risk Trajectory  --  {disp_label.replace('_SM', '')}",
                 fontsize=17, fontweight="bold", y=0.97)
    cohort = "FAILED" if is_failed else "NON-FAILED"
    subtitle = (f"Predictive Intelligence Engine - continuous vehicle health assessment  |  "
                f"{n_days} days  |  {len(traj)} weekly snapshots  |  "
                f"Cohort: {cohort}  |  Final P: {final_p:.2f} ({final_tier})")
    if is_failed:
        subtitle += "  |  Failure signature: " + str(archetype).split("_", 1)[-1].replace("_", " ")
    fig.text(0.5, 0.925, subtitle, ha="center", fontsize=10.5, color="#555555")

    fig.text(0.02, 0.008,
             "DICV Starter Motor Failure Prediction Program | V1.1 | "
             "GREEN <0.35 | AMBER 0.35-0.55 | RED >=0.55 | "
             "risk classification - not a failure-date forecast | Confidential",
             fontsize=8, color="#888888", ha="left", va="bottom")
    # (raw-source traceability footnote omitted in the business variant)
    fig.text(0.98, 0.008,
             f"Starter Motor V1.1 | generated {datetime.now():%Y-%m-%d}",
             fontsize=8, color="#888888", ha="right", va="bottom")

    fig.savefig(str(out_path), dpi=150, bbox_inches="tight", facecolor="white",
                edgecolor="#cccccc")
    plt.close(fig)


# ---------------------------------------------------------------------------
# 8. Run
# ---------------------------------------------------------------------------
def main(vin_list=None):
    if vin_list is None:
        vin_list = sorted(vins, key=lambda v: ("NF" in v,
                                               int(v.replace("VIN", "").split("_")[0])))
    GRAPHS.mkdir(parents=True, exist_ok=True)

    print("\nFitting 34 LOVO-honest fold models (frozen 4 features + per-fold Platt)...")
    models = fit_fold_models()

    print(f"\n{'='*78}")
    print(f"  V1.1 PRODUCTION Starter Motor Risk-Trajectory Dashboards")
    print(f"  Nested-LOVO Ridge (4 feat, AUROC {AUROC_STR}) | VINs: {len(vin_list)}")
    print(f"  Output: {GRAPHS}")
    print(f"{'='*78}\n")

    recon = []
    success, errors = 0, []
    for idx, vin in enumerate(vin_list, 1):
        is_failed = bool(y[vins.index(vin)])
        print(f"  [{idx:2d}/{len(vin_list)}] {vin} ({'FAILED' if is_failed else 'NF'}) ...",
              flush=True)
        try:
            traj = compute_trajectory(vin, models)
            out = GRAPHS / f"V1_1_SM_{display_label(vin)}_dashboard.png"
            plot_dashboard(vin, traj, out)
            p0 = float(traj["p"].iloc[-1])                  # k=0 trajectory score
            off = float(preds.loc[vin, "prob_recal"])       # official OOF recal prob
            recon.append({"vin": vin, "traj_k0": p0, "official": off,
                          "diff": abs(p0 - off)})
            print(f"      traj k=0 P={p0:.4f} | official OOF recal P={off:.4f} | "
                  f"|diff|={abs(p0 - off):.4f}  -> {out.name}")
            success += 1
        except Exception as exc:
            import traceback
            traceback.print_exc()
            errors.append((vin, str(exc)))

    rc = pd.DataFrame(recon)
    print(f"\n{'='*78}")
    print(f"  Done. {success}/{len(vin_list)} dashboards generated.")
    if len(rc):
        worst = rc.loc[rc['diff'].idxmax()]
        print(f"  Reconciliation (traj k=0 vs official OOF recal prob): "
              f"max|diff| = {rc['diff'].max():.4f} ({worst['vin']}), "
              f"median = {rc['diff'].median():.4f}")
        print(f"  Note: diffs arise because the official per-fold pipeline re-selects")
        print(f"  the winner subset inside each fold (24/34 folds = this frozen 4-feature")
        print(f"  subset); the trajectory scorer holds the frozen subset in all folds.")
    if errors:
        print(f"  Errors ({len(errors)}):")
        for vin, err in errors:
            print(f"    {vin}: {err}")
    print(f"{'='*78}\n")


if __name__ == "__main__":
    main(sys.argv[1:] if len(sys.argv) > 1 else None)
